# Generated by Django 2.2.5 on 2020-04-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200407_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='한글',
        ),
    ]
