# Generated by Django 2.2.5 on 2020-04-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200407_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='한글',
            new_name='bio',
        ),
    ]
