# Generated by Django 2.2.5 on 2020-05-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200512_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asdaaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='asdaaw',
            field=models.ManyToManyField(blank=True, to='rooms.Asdaaw'),
        ),
    ]
